### ISSUE TITLE
getting GLTF skinned example to work

### ISSUE THREAD

**Issue by Choons** [panxinmiao/three-py#34]
Hi, thank you for making your three-py project public! I was about to try to port three.js to Python when I found you had already done most of it. I would like to get the three.js example https://threejs.org/examples/webgpu_skinning.html working in three-py and wonder if you can give me any advice on how to proceed? Are there any problems you have run into that I should be aware of?

**Comment by panxinmiao** [comment]
Thank you very much for your interest in this project. The example you mentioned indeed requires an animation engine to load and manage animation data, keyframes, interpolation, and other functionalities. Implementing a universal animation engine is a complex task that requires systematic design and development. Currently, three-py primarily focuses on rendering capabilities and does not have the capability of an animation engine (although we hope to implement it in the future).

In the example you mentioned, it only involves skeletal animation, and three-py already supports skinned meshes. If you are developing specifically for this example, you can try implementing the logic for skeletal animation within your program. You can create your own simple skeletal animation handling code to meet your requirements.

**Comment by Choons** [comment]
Hi, thank you for the prompt reply. I have been studying your morph.py example in comparison to the three,js webgpu_morphtargets example and notice it is quite different. I tried to directly port the three.js example to python, except using your approach of controlling the morph with time instead of by GUI, but it doesn't work. No error is thrown, the cube just doesn't morph. Do you recall why you coded your example so differently?

Here's a link to my code as I ported from three.js to three-py: https://codeshare.io/0gKJvD

**Comment by Choons** [comment]
Here is the code as ported from three.js to three-py:

`import math, time
import three
from wgpu.gui.auto import WgpuCanvas, run



canvas = WgpuCanvas(size=(1200, 675), max_fps=60, title="webgpu_morphtargets")

renderer = three.WgpuRenderer(canvas, antialias = True)
renderer.init()

camera = three.PerspectiveCamera(45, 16/9, 1, 20)
camera.position.z = 10

three.OrbitControls(camera, canvas)

scene = three.Scene()
scene.background = three.Color(0x8FBCD4)

scene.add(three.AmbientLight(0x8FBCD4, 1.5))

pointLight = three.PointLight(0xffffff, 200)
camera.add(pointLight)



def createGeometry():

    geometry = three.BoxGeometry(2, 2, 2, 32, 32, 32)

    # create an empty array to hold targets for the attribute we want to morph
	# morphing positions and normals is supported
    geometry.morphAttributes.position = []

    # the original positions of the cube's vertices
    positionAttribute = geometry.attributes.position
    print("positionAttribute.count", positionAttribute.count) # 6534

    # for the first morph target we'll move the cube's vertices onto the surface of a sphere
    spherePositions = []

    # for the second morph target, we'll twist the cubes vertices
    twistPositions = []
    direction = three.Vector3(1, 0, 0)
    vertex = three.Vector3()

    for i in range(positionAttribute.count):
        
        x = positionAttribute.getX(i)
        y = positionAttribute.getY(i)
        z = positionAttribute.getZ(i)
        
        spherePositions.append(x * math.sqrt(1 - (y * y/2) - (z * z/2) + (y * y * z * z/3)))
        spherePositions.append(y * math.sqrt(1 - (z * z/2) - (x * x/2) + (z * z * x * x/3)))
        spherePositions.append(z * math.sqrt(1 - (x * x/2) - (y * y/2) + (x * x * y * y/3)))	

		# stretch along the x-axis so we can see the twist better
        vertex.set(x * 2, y, z)

        vertex.applyAxisAngle(direction, math.pi * x / 2 ).toArray(twistPositions, len(twistPositions))

    # add the spherical positions as the first morph target
    #geometry.morphAttributes.position[0] = three.Float32BufferAttribute(spherePositions, 3)
    geometry.morphAttributes.position.append(three.Float32BufferAttribute(spherePositions, 3))

    # add the twisted positions as the second morph target
    #geometry.morphAttributes.position[1] = three.Float32BufferAttribute(twistPositions, 3)
    geometry.morphAttributes.position.append(three.Float32BufferAttribute(twistPositions, 3))

    return geometry

def loop():

    now = time.time()
    mesh.morphTargetInfluences[0] = (math.sin(now)+1)/2
    mesh.morphTargetInfluences[1] = (math.cos(now+1)+1)/2    

    renderer.render(scene, camera)


geometry = createGeometry()

material = three.MeshPhongMaterial(color=0xff0000, flatShading=True)

mesh = three.Mesh(geometry, material)

scene.add(mesh)


renderer.setAnimationLoop(loop)

if __name__ == '__main__':    
    run()`

**Comment by panxinmiao** [comment]
Currently, three-py does not have built-in support for morph functionality, So, I actually implemented this part of the logic in this example for test.

**Comment by Choons** [comment]
OK, I'll keep working towards getting the full GLTF spec working with morphs and animations and let you know if I succeed.
