### ISSUE TITLE
UI question

### ISSUE THREAD

**Issue by Choons** [panxinmiao/three-py#35]
Hi, I've been using three-py a lot lately and the more I look at the code, the more impressed I am how much work you did to port it to Python! Anyway, just wondering if you have been using any user interface UI within three-py or as an overlay, and if so would you tell me what you have been using? I noticed wgpu has some Qt references, but I'd like to use something more lightweight, if possible.

**Comment by panxinmiao** [comment]
The GUI is provided and adapted by the wgpu library, and currently wgpu supports glfw, QT, wx, and Jupyter notebook.
